version: "3.8"

services:
  localstack:
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4510-4530:4510-4530"
      - "4566:4566"
      - "4571:4571"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test